# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensetracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
